#服务参数配置
server:
  port: 80
  servlet:
    context-path: /
spring:
  redis:
    host: 172.16.131.10
    port: 6379
    password: 123456
    database: 0
    # 连接超时时间（毫秒）
    timeout:
    # 连接池
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接
        min-idle: 1

# rocketmq的nameserver地址
rocketmq:
  name-server: 172.16.131.16:9876
# 指定生产组名称
  producer:
    group: producer_seckill_grp
    send-message-timeout: 600000